### ISSUE TITLE
Api request limit

### ISSUE THREAD

**Issue by lmfmaier** [chriskonnertz/DeepLy#11]
Hi Chris, just to let you know, the API is currently limited. I still have to figure out if they put a hard limit on the absolute request count from an IP or are just limiting the number of requests within a certain timespan.

One should not currently rely on the API for production use.

Error message: Server side error during DeepLy API call: HTTP code 429, message: "{"jsonrpc": "2.0","error":{"code":1042901,"message":"Too many requests."}}"

**Comment by chriskonnertz** [comment]
Hello,

thank you for this information. I added it to the README.md: https://github.com/chriskonnertz/DeepLy/commit/3e53c06a9dadc4ac590cf37e2484d79d23f1726d

To be honest, I am not suprised since [Linguee.com](https://linguee.com/) - which is made by the makers of DeepL - has a request limit as well.

And even though I'd wish there was no limit it does make sense for an API that is free of cost. (=That is *still* free of cost.)

**Comment by lmfmaier** [comment]
I had email contact with them, they are about to release an official api "very soon", see also https://www.heise.de/newsticker/meldung/Maschinelles-Uebersetzen-Deutsches-Start-up-DeepL-will-230-Sprachkombinationen-unterstuetzen-3836533.html

**Comment by chriskonnertz** [comment]
When did you have email contact with them? The news on Heise.de is from October.

**Comment by lmfmaier** [comment]
Today

**Comment by chriskonnertz** [comment]
Oh, okay. Thank for this hint.

**Comment by chriskonnertz** [comment]
Well I hope they do not start with a closed (with costs) API right from the beginning.

**Comment by MathieuRS1** [comment]
Hi, I have the same problem on nodejs...

"error":{"code":1042901,"message":"Too many requests."

**Comment by chriskonnertz** [comment]
https://www.deepl.com/api-reference.html

> 
> Limits
> 
> The request size should not exceed 30kbytes. The maximum number of texts to be translated within one request should not exceed 50.
> 
> Please ensure your client does not exceed the limits as specified in the quota documentation delivered to you. Your client should be prepared to back-off if you receive the HTTP response code 429 and retry the request later.
