### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by chriskonnertz** [chriskonnertz/DeepLy#13]
The DeepL docs says that there will be an API key. DeepLy 2 will support the usage of this API key.

Development will happen on this branch: 
https://github.com/chriskonnertz/DeepLy/tree/2.0

**Comment by glemmal** [comment]
is this enhancement already mergable? I noticed that deepl now started the premium program on their website. Thank you very much for your client!

**Comment by chriskonnertz** [comment]
Hello, unfortunaetly this branch is not ready to be merged. 

I will try to finish it as soon as possible. However, I still try to figure out if there is a way to avoid the costs of the premium program since this is a free open source library that does not create any revenue...

**Comment by scribnermj** [comment]
I didn't see anything about a transition from public access to premium service on their web site. Did I miss it?

**Comment by chriskonnertz** [comment]
"DeepL Translator" also know as their online translation tool still is non-premium.

However, they recently released "DeepL Pro" which includes access to their API via an API authentication key. "DeepL Pro" is a premium service.

_Officially_ the API never has been meant to be accessible for the public. However, since "DeepL Translator" uses their API and thus makes API calls from a client it is possible to use there API without an API key.

**Comment by chriskonnertz** [comment]
I have sent them a mail. I asked them if they offer any support for open source development. I do want to avoid paying 20 € to get access to their API to develop a non proft software. I will wait until they answer before taking further action.

**Comment by scribnermj** [comment]
It seems a bit premature to start charging for the service right now.
Both Bing and Google offer better service with many more languages and very competitive pricing as far as I can tell.

**Comment by chriskonnertz** [comment]
I do not judge. However, I assume other than Google and MS they really need to make money with this service.

**Comment by scribnermj** [comment]
I get it too. Not judging. Just expressing my view on it. It's pretty handy for my needs. I'll be disappointed if and when I get shut out .

**Comment by chriskonnertz** [comment]
@glemmal

> is this enhancement already mergable?

Update:

The branch is not mergable, however, I believe it might work. I have not DeepL Pro access, therefore I have no API key and cannot test the branch. However, it *might* work. Feel free to test it :P

**Comment by glemmal** [comment]
@chriskonnertz sorry for the late reply. I already tested the branch and it doesn't seem to work that way. It only accepts the api key via query param. i have a quick and dirty working example that looks like this:
![image](https://user-images.githubusercontent.com/3272297/38137389-a3f5072c-3424-11e8-8a54-783bda0d1396.png)
Anyways i will come up with a working PR soon :)

**Comment by chriskonnertz** [comment]
> I already tested the branch and it doesn't seem to work that way

Argh. Sad.

> Anyways i will come up with a working PR soon :)

That would be great!!

**Comment by inovek** [comment]
Hello @chriskonnertz,

I would suggest to think about again, to implement the API into the workflow.  DeepL has **changed the price-model** again to much more fair conditions. ( starts with € 5.99 )

https://www.deepl.com/pro.html

I would like to add a custom api-key to the workflow, because the starter-account is that what firts best for private-usage and feels also fair. I'm a huge fan of Linguee and now also for DeepL, so I would like to support them with a fair usage and price.

They really gave and delivered us a good service, which should be honoured.

**Comment by chriskonnertz** [comment]
Hello @inovek ,

you are right and in generally I do want to support DeepL pro. It's just a question of time.

**Comment by chriskonnertz** [comment]
Finally done, only took 4 years  💥
