### ISSUE TITLE
Very complex your code

### ISSUE THREAD

**Issue by sysmaya** [chriskonnertz/DeepLy#16]
Nice but very granurality. over 10 class... 👎 
Simply is Best.
One simply function.

`$rta = translate('Hola todos, espero que hoy tengan un buen dia.');
    print_r($rta); `

`    
 
    function translate($text, $from='LANG_ES', $to='LANG_EN'){
    $params =             ['lang'  => [ 'ser_preferred_langs' => ['LANG_ES', 'LANG_EN'], 'source_lang_user_selected' => 'LANG_ES', 'target_lang' => 'LANG_EN', ] ];
    $params['jobs'][0] =  [ 'kind' => 'default', 'raw_en_sentence' => $text ];
    $data = ['jsonrpc' => '2.0', 'method'  => 'LMT_handle_jobs', 'params'  => $params, 'id' => '2', ];
    $data = json_encode($data);

    $curl = curl_init('https://www.deepl.com/jsonrpc/');
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, true);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json', 'Content-Length: ' . strlen($data))  );
    $rawResponseData = curl_exec($curl);
    $rawResponseData = json_decode($rawResponseData);
         
    return $rawResponseData;    
    }`

**Comment by chriskonnertz** [comment]
Hello

> Nice 

Thank you.

> but very granurality. over 10 class... 👎

Debatable. The "core" of the library has only 6 classes:
* `DeepLy` (main class)
* `HttpClient\CurlHttpClient` (HTTP client class)
* `Protocol\JsonRpcProtocol` (JSON RPC is the protocol used by the DeepL API)
* `ResponseBag\AbstractBag` (Base wrapper class for the responses of the DeepL API)
* `ResponseBag\SentencesBag (concrete class for API responses to "split text" requests)
* `ResponseBag\TranslationBag (concrete class for API responses to "translate" requests)

These are the classes that are essential and include code that can be executed.
There are other classes that do not contain  code that can be executed: exception classes and interfaces.
Plus there is an alternative HTTP client implementation, a wrapper for Guzzle. You do not have to use it.
Last but not least there are two classes that add integrate the library in Laravel applications. You do not have to use these classes.

**Comment by chriskonnertz** [comment]
> One simply function.
You are assuming that Spanish is the default language. I assume that you do agree to that being not a solution one could use in a library created for usage all over the world. It's a nice shortcut but it does not work for DeepLy. But what you could do is  this:

```php
function translate($text, $from='LANG_ES', $to='LANG_EN') {
  $deepLy = new ChrisKonnertz\DeepLy\DeepLy();
  return $deepLy->translate($text, $to, $from);
}
```

**Comment by chriskonnertz** [comment]
However, thank you for yout feedback. I have added the "class overview" to the README.md. This seems to be useful information and should help others to understand the internals of DeepLy.

https://github.com/chriskonnertz/DeepLy/commit/8cfc0acbe214794d8f3ea9113fa1614c2e5cbc43
