### ISSUE TITLE
What after getting 429 error.

### ISSUE THREAD

**Issue by D-David11** [chriskonnertz/DeepLy#18]
Hello,

I am getting 429 request limit error. After how many time I can re-request for translation. When this error gone ?

**Comment by chriskonnertz** [comment]
Hello,

let me start with a clarification: DeepLy is a client for the DeepL.com translation API. The limit is set by the API, not by the client. 

Here is what the official API documentation has to say about that topic:
https://www.deepl.com/api.html

>Code 429 Description Too many requests. Please wait and send your request once again.

> Please ensure your client does not exceed the limits as specified in the quota documentation delivered to you. Your client should be prepared to back-off if you receive the HTTP response code 429 and retry the request later.

I asume if you use "DeepL Pro" (their premium service) you will get that "quota documentation" that specifies the request limits. 

IF you do not use "DeepL Pro" the request limit is unknown.

**Comment by D-David11** [comment]
After how many time I can retry for translation

**Comment by chriskonnertz** [comment]
Again, that remeains unknown since DeepL has not released any information about this topic. (At least not in their official API documentation.)

I would like to give you a better answer but I do not work for DeepL.

**Comment by D-David11** [comment]
Ok thanks man.
