### ISSUE TITLE
Deepl Pro with your lib

### ISSUE THREAD

**Issue by D-David11** [chriskonnertz/DeepLy#19]
Hello,

I was using your lib with deepl but now I have purchased DeepL Pro, will your code work with pro ? And can you please tell me where I can use Auth Key in your code ?

Thanks.

**Comment by scribnermj** [comment]
You have done a great job here Chris.

**Comment by D-David11** [comment]
Hello

Thanks for your replay.

I downloaded https://github.com/chriskonnertz/DeepLy/tree/2.0 and used it with pro auth key.

Its seems it is working. But In my DeepL account in usage menu it is not displaying used character. So I am confused.

I just replace you old lib with this new 2.0 and passed API key.

**Comment by chriskonnertz** [comment]
DeepLy 2 is under development and will be released soon. It will support DeepL Pro. I recommend to switch to DeepLy 2 as soon as possible.
