### ISSUE TITLE
Always get 'Too many request'

### ISSUE THREAD

**Issue by brentrug** [chriskonnertz/DeepLy#20]
Hi i use your plugin to translate my website, and I love it!

From time to time i get an error "Too many request", if I used the API to much. After some time it worked again.

But since today, I get it from the start...

Do you think they changed something, so that this plugin is not working anymore?

Best
Beat

**Comment by chriskonnertz** [comment]
Hello,

thank you for reporting this behaviour. I'm going to check it.

**Comment by chriskonnertz** [comment]
Yep, getting the same response.

**Comment by chriskonnertz** [comment]
a) The API has changed
b) Using the API without an API key is no longer possible

**Comment by chriskonnertz** [comment]
Just for your information, I seek to (finally) add support for authentication. Doing so should answer the question if  a) or b) is the reason.

However, there is no schedule yet.

**Comment by brentrug** [comment]
Do you have any idea, when you will include the API auth. into deeply?

**Comment by chriskonnertz** [comment]
DeepLy 2 is under development and will be released soon. It will support DeepL Pro. I recommend to switch to DeepLy 2 as soon as possible.

**Comment by chriskonnertz** [comment]
It work's (again) => https://github.com/chriskonnertz/DeepLy/releases/tag/v1.6.0
so I'm closing this issue.
