### ISSUE TITLE
Pro version: Server side error during DeepLy API call: HTTP code 429, message: "{"jsonrpc": "2.0","error":{"code":     1042901,"message":"Too many requests."}}"

### ISSUE THREAD

**Issue by kylescousin** [chriskonnertz/DeepLy#23]
I'm providing an API key on instantiation and still getting this request limit.

What to do about it? I barely made 10 translations.

**Comment by rubo77** [comment]
I worked around in my script that way, that I only make one request per hour. I am OK with my translation if it finishes within a few days ;)

**Comment by ghprod** [comment]
@kylescousin do you use the starter plan?

**Comment by chriskonnertz** [comment]
This library now supports the pro plan.
