### ISSUE TITLE
always  Server side error during DeepLy API call: HTTP code 429, message: "{"jsonrpc": "2.0","error":{"code":1042902,"message":"Too many requests."}}"

### ISSUE THREAD

**Issue by Dao258** [chriskonnertz/DeepLy#25]
I always got this info  
Server side error during DeepLy API call: HTTP code 429, message: "{"jsonrpc": "2.0","error":{"code":1042902,"message":"Too many requests."}}"

Is it able to fix?

Thanks in advance.

**Comment by chriskonnertz** [comment]
Hello,

probaply this is not fixable. We are using their API that actually is not meant to be used without an API key, so yeah, problems are likely. :(

**Comment by liyuanzao** [comment]
Hi, Chris

I’d like to purchase an api from deepl.

If your code 2.0 is release, will starter subscription work for the code ?

Thanks !

~Howard

**Comment by chriskonnertz** [comment]
Hello,

I don't know, you have to ask DeepL...

**Comment by chriskonnertz** [comment]
Use the new versino of this liabry with a free or pro plan.
