### ISSUE TITLE
Use /languages endpoint

### ISSUE THREAD

**Issue by caugner** [chriskonnertz/DeepLy#26]
DeepL now provides an API endpoint to list the supported languages: https://www.deepl.com/docs-api/other-functions/listing-supported-languages

Using this endpoint avoids having to adapt the library for every new language.

**Note**: With `PT-BR` and `PT-PT`, DeepL now also supports two variations: https://www.deepl.com/en/blog/20200402.html

**Comment by chriskonnertz** [comment]
Hello @caugner ,

so can I add them just as any other language? I guess: yes?

**Comment by caugner** [comment]
> so can I add them just as any other language? I guess: yes?

Yes, for now you can add them like any other languages (i.e. all uppercase, "PT" is still supported and equivalent to `PT-PT`).

For the future it would be nice to retrieve the list of supported languages directly from their endpoint.

**Comment by caugner** [comment]
@chriskonnertz DeepL also supports Japanese (`JA`) and Chinese (`ZH`) since March.

**Comment by chriskonnertz** [comment]
Languages updated.

Decided not to use the language update and rather hard-code the list to avoid trouble.
