### ISSUE TITLE
Open DeepL Translator Pro using authentication (without login) 

### ISSUE THREAD

**Issue by fmourtaza** [chriskonnertz/DeepLy#29]
Hello Chriskonnertz,

This could be a general question.

Our organization wanna open a translator for all employees, therefore they want to keep the translator link in the intranet.

So once the user opens the translator page, he/she must open the page with DeepL Pro (without explicit login) - how can we achieve that? is there any automatic OAuth API provided by DeepL?

Thanks in advance.

Best regards.

**Comment by chriskonnertz** [comment]
Hello,

please contact Deepl.com support: 

support.deepl.com/hc/en/requests/new
