### ISSUE TITLE
Finalize keep-line-breaks feature

### ISSUE THREAD

**Issue by chriskonnertz** [chriskonnertz/DeepLy#3]
Branch: https://github.com/chriskonnertz/DeepLy/tree/feature-keep-line-breaks

Todo:
- Avoid individual split-sentence calls for all lines
- Udpate README.MD
- Test
- Adjust tests
- Release new version

**Comment by scribnermj** [comment]
In my testing of this code on my local server using the web pages supplied. I was unable to get a translation fed back to me. I removed the current loop that added the php_eol and replaced it with a single line as shown below. I saw no issues with this, tho I am not aware of the full range of capabilities that might be affected.

$translatedText .= PHP_EOL;

For the sake of sharing only, I would add, that I had an issue also with SSL certificate errors which forced me to use the ignore logic as stated in the source.  Also, on the web pages themselves, for my software and internet connection, I have to disable the HTTP requests. 

Overall, I am very pleased with the code. It is quite comprehensive.

**Comment by chriskonnertz** [comment]
Hello,

thank you for your feedback! It is very helpful to get such kind of feedback.

The PHP_EOL loop is meant to add multiple line breaks if there is a "cluster" of empty lines, for example:

```
Hello, world!


Hello, world!
```

So removing the loop may fix the issue you have seen but then multiple empty lines will no longer get recreated. I made a commit that changed something and might fix the issue: https://github.com/chriskonnertz/DeepLy/commit/dae35291e95c17ba0f5b067f81e5ca49ec1cea78

**Comment by chriskonnertz** [comment]
Done: https://github.com/chriskonnertz/DeepLy/releases/tag/v1.5.0
