### ISSUE TITLE
DeepLy Installation

### ISSUE THREAD

**Issue by menexa** [chriskonnertz/DeepLy#4]
This project seems really interesting but I wasn't able to test it on my web server.
I have a virtual server with Plesk 12.5 and I tried to follow the directions on https://docs.plesk.com/en-US/12.5/administrator-guide/website-management/websites-and-domains/web-applications/managing-php-project-dependencies-with-composer.74969/ but without good results.
Can you tell me how I should proceed, step by step, starting from the DeepLy-master.zip file?

**Comment by chriskonnertz** [comment]
Hi, I will reply tomorrow.

**Comment by chriskonnertz** [comment]
Hello,

there are two ways. 

The fast and lazy way: [Download](https://github.com/chriskonnertz/DeepLy/archive/master.zip) the code as a .zip file, then extract it loally on your computer and upload all files to your web server.

The better way: I belive the problem Plesk has is that in your PHP project you need to have a `composer.json´ file that tells Composer which dependencies (DeepLy in this case) your project has. So I assume you have to create one on your local computer, upload it to your web server and move it to your HTML / public directory. The content of the file may look like this:

```
{
  "require": {
    "chriskonnertz/deeply": "^1.4"
  }
}
```

(More details: https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup )
