### ISSUE TITLE
English text gets translated to french 

### ISSUE THREAD

**Issue by lmfmaier** [chriskonnertz/DeepLy#9]
When I call $deepLy->translate($text, 'EN', 'DE') deepLy returns french text when the original text ist aready english or mixed english/german (I don't do language checks, because sometimes we have mixed language texts.

Test case:

$deepLy = new ChrisKonnertz\DeepLy\DeepLy();
echo $deepLy->translate("Doors: 8pm Father Sky Mother Earth has released two monumental meditative albums since the beginning in autumn 2016. „Across the River of Time“ is an atmospheric journey through your own universe. Dark, intense and ecstatic: The Drone Doom Duo let’s you forget space and time. MAENTIS ist eine Doom Sludge Band aus Hildesheim. Das 2015 gegründete Quartett (Alexander Seidel & Jan Gibron – Gitarre, Björn Behrens – Bass, Andy Krüßel – Schlagzeug + Stimme) lässt massive Klangwände mit kalter, klirrender Psychedelik verschmelzen: der Zuhörer verfängt sich in einem Sog der transzendentalen Dunkelheit. Das Debut-Album I HAVE TASTED DEVIL’S BLOOD wird als eines der besten instrumentalen Sludge/Doom-Veröffentlichungen 2016 angesehen.",'EN','DE');

This also happens when I set source language to auto or EN.

And it also happens when I pass english strings with auto source or EN as source:

$deepLy = new ChrisKonnertz\DeepLy\DeepLy();
echo $deepLy->translate("Thunder and lightning",'EN');
echo $deepLy->translate("Thunder and lightning",'EN','EN');

This leaves the short source string in english, but doesnt work for the mixed longer text above:

echo $deepLy->translate("Thunder and lightning",'EN','DE');

**Comment by chriskonnertz** [comment]
Hello,

you do use version 1.5.0 of DeepLy? (-> please take a look at `DeepLy::VERSION` if you are not sure)

**Comment by lmfmaier** [comment]
Hi Chris,

yes it's a fresh install and, version is 1.5.0. It's PHP7 on Debian 9

**Comment by chriskonnertz** [comment]
Okay, strange. I have trouble to reproduce the behaviour that you expierienced.

When I let DeepLy translte your text from 'EN' to 'DE' it returns this translations:

> Doors: Father Sky Sky Mother Earth hat seit Herbst 2016 um 20 Uhr zwei monumentale meditative Alben veröffentlicht,"Across the River of Time" ist eine atmosphärische Reise durch das eigene Universum. Dunkel, intensiv und ekstatisch: Das Drone Doom Duo lässt Sie Raum und Zeit vergessen. MAENTIS ist eine Doom Schlammband aus Hildesheim. Das 2015 gegründete Quartett (Alexander Seidel & Jan Gibron - Gitarre, Björn Behrens - Bass, Andy Krüßel - Schlagzeug + Stimme) lässt massive Klangwände mit kalter, klirrender Psychedelik verschmelzen: der Zuhörer verfängt sich in einem Sog der transzendentalen Dunkelheit. Das Debut-Album I HAVE TASTED DEVIL' S BLOOD wird als eines der besten instrumentalen Schlamm/Doom-Veröffentlichungen 2016 angesehen.

Obviously it works. 

Can you please call `$deepLy_>translate(...)`and then: 
```
$bag = $deepLy->getTranslationBag;
var_dump($bag);
```
And post the result of the var_dump() call here?

**Comment by lmfmaier** [comment]
When I translate from EN to DE I get the same result. When I translate from DE to EN, the English part of the text should remain the same while the German part should be translated to English.  But the English part is translated to French, which is strange indeed and the German part isn't translated at all ;)

This is the code I have run a few minutes ago:

deepLy = new ChrisKonnertz\DeepLy\DeepLy();

echo $deepLy->translate("Doors: 8pm Father Sky Mother Earth has released two monumental meditative albums since the beginning in autumn 2016. „Across the River of Time“ is an atmospheric journey through your own universe. Dark, intense and ecstatic: The Drone Doom Duo let’s you forget space and time. MAENTIS ist eine Doom Sludge Band aus Hildesheim. Das 2015 gegründete Quartett (Alexander Seidel & Jan Gibron – Gitarre, Björn Behrens – Bass, Andy Krüßel – Schlagzeug + Stimme) lässt massive Klangwände mit kalter, klirrender Psychedelik verschmelzen: der Zuhörer verfängt sich in einem Sog der transzendentalen Dunkelheit. Das Debut-Album I HAVE TASTED DEVIL’S BLOOD wird als eines der besten instrumentalen Sludge/Doom-Veröffentlichungen 2016 angesehen.",'EN','DE');

$bag = $deepLy->getTranslationBag();
var_dump($bag);

Here's the vardump, it also says target is FR:

object(ChrisKonnertz\DeepLy\ResponseBag\TranslationBag)[133]
  protected 'lineBreaks' => 
    array (size=0)
      empty
  protected 'responseContent' => 
    object(stdClass)[129]
      public 'source_lang' => string 'EN' (length=2)
      public 'source_lang_is_confident' => int 1
      public 'target_lang' => string 'FR' (length=2)
      public 'translations' => 
        array (size=5)
          0 => 
            object(stdClass)[124]
              ...
          1 => 
            object(stdClass)[122]
              ...
          2 => 
            object(stdClass)[119]
              ...
          3 => 
            object(stdClass)[114]
              ...
          4 => 
            object(stdClass)[111]
              ...

**Comment by lmfmaier** [comment]
Thanks for your work on this btw.

I'm super hyped that there is finally proper Api access to deepL, because the results are so much better than Google's

**Comment by chriskonnertz** [comment]
>  When I translate from DE to EN, the English part of the text should remain the same while the German part should be translated to English. But the English part is translated to French, which is strange indeed

Ok, when I let it translate from DE to EN I get the same result. I believe that DeepL tries to detect the "primary" language of the text and it decides that it is English. (I have no idea why it chooses English.)

If I am right and DeepL believes that this is an English text, it does not make sense to translate from English to English so it switches the target language to something else, French in this case.

The problem is that as far as I understand the API does not offer a way to assign a language on a per sentence base. (This is speculation of course since we do know the API specification.) I will try to take a look at the other API clients and check if they have a solution, but I do not think so.

> I'm super hyped that there is finally proper Api access to deepL, because the results are so much better than Google's

Yep, much better. So much better that I am afraid they will not only force clients to use an API key (I am almost sure they will do that) but also let all users of the API pay for the access. :(

**Comment by lmfmaier** [comment]
No problem here with paid services as long as they deliver quality.  We are currently paying for Google Translate and the results are mostly underwhelming.  I was totally amazed with the quality of deepL, i hope they don't get acquired by big G all too soon ;)

Thanks for your effort. I will try to split the larger texts into smaller pieces based on paragraphs, this seems to work

**Comment by chriskonnertz** [comment]
They said that they do not want to get acquired.

**Comment by scribnermj** [comment]
I'm not entire sure about google, but I know that Microsoft translate api was a free product with the intent of drawing away paid subscribers from google.  I expect deepl will want to develop a base of potential customers before they start charging and or using oauth access.

**Comment by chriskonnertz** [comment]
Well, let's hope that you are right.
